### ISSUE TITLE
Latest Developers Documentation lacks information on IMA, Zniffer..

### ISSUE THREAD

**Issue by pz1** [Z-Wave-Me/Z-Way-Manual#10]
The Z-Way Develop ers Documentation (c) Z-Wave.Me Team, based on Version 2.2.4 that I found on Github today lacks references to ZNiffer, IMA and possibly a few other recently introduced concepts. Since I can't find e.g. Zniffer in my v2.2.4 (final) upgrades and also not in a newly setup machine. I had hoped to find some references in this document

**Comment by PoltoS** [comment]
It is still in development and will be documented once implemented in final version,

**Comment by pz1** [comment]
In the 2.2.4 release notes I read

> - New controller.data.outgoingPacket and controller.data.incomingPacket for sniffer tool. Now you can see all packets in and out!

Because I did not see that sniffer functionality, I looked into the v2.2.4 based developers manual for some more help
