### ISSUE TITLE
Implement https://www.sharelatex.com

### ISSUE THREAD

**Issue by jhmartin** [Z-Wave-Me/Z-Way-Manual#5]
You might consider splitting the different manuals into separate repositories and have https://www.sharelatex.com/github/ auto-rebuild them whenever a commit occurs.

**Comment by PoltoS** [comment]
Nice idea, thanks. We will consider it

**Comment by jhmartin** [comment]
On a related note, the pdfs should be uploaded as 'releases' rather then checked into the repository, as they are binary release artifacts. https://github.com/blog/1547-release-your-software
